### PR TITLE
AllAnime [EN]: Fix video extraction with AES-256 decryption

### LINKED ISSUE #157: AllAnime no video found
### Source information

AllAnime 14.46

### Source language

English

### Steps to reproduce

I opened an Anime from AllAnime source but it can't fetch the episode

### Expected behavior

It should also be able to download and watch episode

### Actual behavior

This is the error both download and watch

Image

Image

### Which app are you using?

Aniyomi

### App version

0.18.1.2

### Android version

Android 15.1.2

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to **[latest version](https://github.com/komikku-app/anikku/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://anikku-app.github.io/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/yuzono/anime-extensions/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 7heMech**
Closes #157 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension
- [x] Have made sure all the icons are in png format

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/yuzono/anime-extensions/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

## Summary by Sourcery

Handle AllAnime episode stream responses that may be AES-encrypted and ensure video extraction continues to work.

Bug Fixes:
- Restore video list extraction when the AllAnime API returns AES-256-GCM–encrypted episode data by decrypting the payload before processing.
- Gracefully fall back to legacy plain JSON parsing when the encrypted episode payload is missing or malformed.

Enhancements:
- Introduce DTOs for encrypted and decrypted episode responses and reuse shared JSON helper utilities instead of a lazily injected Json instance.
- Simplify preference handling by relying on default ListPreference and MultiSelectListPreference persistence behavior.
- Use shared helpers for JSON body construction and response reading in network requests.

Build:
- Bump the AllAnime extension version code to 47.

### CODE REVIEW

**Comment by 7heMech** [comment]
I managed to test and it works.

File: src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt [hunk 1]
```diff
@@ -301,8 +306,27 @@ class AllAnime :
 
     override suspend fun getVideoList(episode: SEpisode): List<Video> {
         val response = client.newCall(videoListRequest(episode)).await()
```
Comment (cuong-tran) [inline src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt]: Should have followed the suggestion:
```suggestion
        val responseBody = client.newCall(videoListRequest(episode)).awaitSuccess().bodyString()
```

File: src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnimeDto.kt [hunk 2]
```diff
@@ -133,3 +133,18 @@ data class EpisodeResult(
         }
     }
 }
+
+@Serializable
+data class EncryptedEpisodeResult(
+    val data: EncryptedData
```
Comment (cuong-tran) [inline src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnimeDto.kt]: Ktlint should have automatically fix this lint error if you compile and test with AndroidStudio. Weird.

File: src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt [hunk 3]
```diff
@@ -301,8 +306,27 @@ class AllAnime :
...
+        val responseBody = response.body.string()
+
+        // 1. Try parsing the encrypted wrapper
+        val encryptedJson = runCatching {
+            json.decodeFromString<EncryptedEpisodeResult>(responseBody)
```
Comment (cuong-tran) [inline src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt]: Can use `Json` helper methods

**Comment by cuong-tran** [comment]
@sourcery-ai review

**Comment by 7heMech** [comment]
Using AI to the max hah

**Comment by cuong-tran** [comment]
It can detect potention issues so use it for review is quite efficient
