### PR TITLE
AnimePahe: Fix video loading

### LINKED ISSUE #134: Animepahe no video found
### Source information

Animepahe 14.37

### Source language

English

### Steps to reproduce

Play episode in Animepahe extension

### Expected behavior

It should be able to fetch the video

### Actual behavior

Instead **No Available Videos**  and I tried in Webview and it works. It's just that the  **.pw/a/(anime)** automatically changes to **.pw/anime/(anime)**. I don't know if this is the problem but. I hope it will be fixed

### Which app are you using?

Aniyomi

### App version

0.18.1.2

### Android version

Android 15.1.2

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to **[latest version](https://github.com/komikku-app/anikku/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://anikku-app.github.io/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/yuzono/anime-extensions/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Alpha-782**
Fixed how extension grabs video links.  Addresses error 403: Forbidden error.
Added specific changes, notably user agent to fix loading issues.
Bumped to version 38.
Closes #134.

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension
- [ ] Have made sure all the icons are in png format

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/yuzono/anime-extensions/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by Alpha-782** [comment]
No videos in Aniyomi. Works fine on Anikku.

**Comment by Alpha-782** [comment]
Closes #134.

**Comment by cuong-tran** [comment]
I think it's failed again.

**Comment by Alpha-782** [comment]
Checking on my side.

**Comment by cuong-tran** [comment]
I think I know why. This fix the case when using HLS.

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt [hunk 1]
```diff
@@ -327,16 +327,32 @@ class AnimePahe :
     }
 
     private suspend fun getVideo(paheUrl: String, kwikUrl: String, quality: String): Video {
+        val normalizedKwikUrl = when {
```
Comment (cuong-tran) [inline src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: Why need to normalize? Could you give an example series where this is needed?

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt [hunk 2]
```diff
@@ -327,16 +327,32 @@ class AnimePahe :
...
         return Video(
             videoUrl,
             quality,
             videoUrl,
-            headers = Headers.headersOf("referer", "https://kwik.cx"),
+            headers = Headers.headersOf(
+                "referer",
+                normalizedKwikUrl,
+                "origin",
+                "https://kwik.cx",
```
Comment (cuong-tran) [inline src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: Only need the trailing slahs "/" to the end of `referer` is enough

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt [hunk 3]
```diff
@@ -327,16 +327,32 @@ class AnimePahe :
...
     private suspend fun getVideo(paheUrl: String, kwikUrl: String, quality: String): Video {
+        val normalizedKwikUrl = when {
+            kwikUrl.startsWith("//") -> "https:$kwikUrl"
+            kwikUrl.startsWith("http") -> kwikUrl
+            else -> "https://$kwikUrl"
+        }
+
         val videoUrl = if (preferences.getBoolean(PREF_LINK_TYPE_KEY, PREF_LINK_TYPE_DEFAULT)) {
-            KwikExtractor(client).getHlsStreamUrl(kwikUrl, referer = baseUrl)
+            KwikExtractor(client).getHlsStreamUrl(normalizedKwikUrl, referer = baseUrl)
```
Comment (cuong-tran) [inline src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: Since currently only the MP4 option is working, maybe force it in code (temporarily)

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt (hunk 1 above)
Comment (Alpha-782) [reply src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: Ah you're right. No need for it. Got rid of it.

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt (hunk 3 above)
Comment (Alpha-782) [reply src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: Will do. Option still there, but won't function.

**Comment by Alpha-782** [comment]
Should work fine again.

**Comment by Alpha-782** [comment]
Still fails in Aniyomi, but I can't figure out why.

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt [hunk 4]
```diff
@@ -317,29 +316,30 @@ class AnimePahe :
...
 
-    private suspend fun getVideo(paheUrl: String, kwikUrl: String, quality: String): Video {
-        val videoUrl = if (preferences.getBoolean(PREF_LINK_TYPE_KEY, PREF_LINK_TYPE_DEFAULT)) {
-            KwikExtractor(client).getHlsStreamUrl(kwikUrl, referer = baseUrl)
-        } else {
-            KwikExtractor(client).getStreamUrlFromKwik(paheUrl)
-        }
+    private suspend fun getVideo(paheUrl: String, quality: String): Video {
+        // Temporarily forcing the MP4 extraction as HLS is currently broken.
+        // Also bypasses the PREF_LINK_TYPE_KEY preference check.
```
Comment (cuong-tran) [inline src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: you got it the other way around. Should use the other HLS method.
Also while you are at it, fix the `referer = baseUrl` to `referre = "$baseUrl/"` too.

Comment out the `...StreamUrl...` one so we can get back to it later.

Honestly though, I'm not really sure we should overwrite this, or leave it as before and manually tell users to use HLS.

Comment (Alpha-782) [reply src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt]: Let me do that real quick.

**Comment by Alpha-782** [comment]
Tried your fix on my end. Works on both Anikku and Aniyomi. Of course, HLS needs to be on in settings.
